AllCops:
 # Include gemspec and Rakefile
 Include:
   - '**/*.gemspec'
   - '**/Rakefile'
 Exclude:
   - 'db/**/*'
   - 'config/**/*'
   - 'script/**/*'
   - 'vendor/**/*'
 RunRailsCops: true
Style/AsciiComments:
 Enabled: false
Style/Documentation:
 Enabled: false
# 1.9 style hash
Style/HashSyntax:
 Enabled: false
Metrics/MethodLength:
  # Enabled: false
  Max: 20
Metrics/LineLength:
  Max: 100
Metrics/AbcSize:
  Enabled: false
#Metrics/PerceivedComplexity:
#  Enabled: true